### ISSUE TITLE
Error reading GRIB data when update MATLAB to 2017b

### ISSUE THREAD

**Issue by tfoterye** [nctoolbox/nctoolbox#111]
A program has been written to read GRIB2 data by nctoolbox. It could be run in MATLAB 2017a and before. However, when I update MATLAB to 2017b, an error has occured as this:

> Error using ncdataset (line 97)
> Failed to open _FNL_fnl_20170221_06_00.grib2
> 
> Error in cfdataset (line 59)
>             obj = obj@ncdataset(url);
> 
> Error in ncgeodataset (line 74)
>             obj = obj@cfdataset(url);
> 
> Error in drawGrib2 (line 4)
> nc=ncgeodataset(filename);
> 
> Caused by:
>     Error using ncdataset (line 81)
>     Java exception occurred:
>     java.io.IOException: java.lang.RuntimeException: java.lang.NoClassDefFoundError:
>     ucar/nc2/util/CloseableIterator
> 
>     	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:425)
> 
>     	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:699)
> 
>     	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:421)
> 
>     	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:404)
> 
>     	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:389)
> 
>     	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:376)
> 
>     Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: ucar/nc2/util/CloseableIterator
> 
>     	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1557)
> 
>     	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:813)
> 
>     	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:422)
> 
>     	... 5 more
> 
>     Caused by: java.lang.NoClassDefFoundError: ucar/nc2/util/CloseableIterator
> 
>     	at ucar.nc2.grib.grib2.Grib2CollectionBuilder.<init>(Grib2CollectionBuilder.java:109)
> 
>     	at
>         ucar.nc2.grib.grib2.Grib2CollectionBuilder.readOrCreateIndexFromSingleFile(Grib2CollectionBuilder.java:75)
>         
>     	at ucar.nc2.grib.GribIndex.makeGribCollectionFromSingleFile(GribIndex.java:122)
> 
>     	at ucar.nc2.grib.grib2.Grib2Iosp.open(Grib2Iosp.java:311)
> 
>     	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1521)
> 
>     	... 7 more
> 
>     Caused by: java.lang.ClassNotFoundException: ucar.nc2.util.CloseableIterator
> 
>     	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 
>     	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 
>     	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
> 
>     	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 
>     	... 12 more

I wanna to know whether this phemenon has also occured in other's MATLAB and how to fix it.
Thanks for your reading!

**Comment by rsignell-usgs** [comment]
Did you get any errors or messages when you ran setup_nctoolbox in Matlab 2017b?

Is any file working for you in nctoolbox with Matlab 2017b or is only this grib file that is giving problems?

**Comment by tfoterye** [comment]
@rsignell-usgs Thanks for your reply! No error and warning has been displayed when I ran setup_nctoolbox. I have tried several GRIB2 files and they all have the same problem. I will try some other kind of files to see whether there will be the same answer.

**Comment by helsharif** [comment]
Hello, I am also having the same problem in Matlab 2017b trying to open GRIB2 files. Here is a link to a zip file containing the GRIB2 file I was trying to open using NCTOOLBOX:
https://www.dropbox.com/s/ills9ohli8lqltj/gfs_4_20160106_0000_003.zip?dl=0

**Comment by greensunrise** [comment]
I am also experiencing this error in MATLAB 2017b.

**Comment by tfoterye** [comment]
@helsharif I have  changed my version to 20120109, and it seems to work well.

**Comment by tfoterye** [comment]
@helsharif  I have changed my nctoolbox version to 20120109, and it seems to work well.

**Comment by tfoterye** [comment]
@greensunrise I have changed my nctoolbox version to 20120109, and it seems to work well.

**Comment by tfoterye** [comment]
@rsignell-usgs It seeems that it is the problem of java version. My Java version is 'Java 1.8.0_121-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode'. I am trying to install 1.6, then I'll test whether the problem will occur pr not.

**Comment by tfoterye** [comment]
@rsignell-usgs It seems that it is the problem of java version. My Java version is 'Java 1.8.0_121-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode'. I am trying to install 1.6, then I'll test whether the problem will occur pr not.

**Comment by carmenuni** [comment]
Hi people, 
I'm using Matlab Version R2018a,  nctoolbox 1.1.3 and I am experiencing the same problem.. As I read on an older feed there is a problem with the matlab-own java version that is loaded instead of the protobuf-java that is in the toolbox.  
 See this link to understand what I mean https://github.com/nctoolbox/nctoolbox/issues/3

However, I did excatly what I was told in the link above (created the javaclasspath file with the path and the <before>) and I still end up with the same problem. 
It says 'Failed to open (filename)' and this long error message that is shown above. 

As I cannot do anything with the code like this I would be really happy if anyone can provide possible solutions to this problem. 
Thanks!

**Comment by helsharif** [comment]
Hi, the easiest workaround I found was to use an earlier version of Matlab whenever I want to use the nctoolbox

**Comment by adamcandy** [comment]
Likely cause: An optional toolbox.
Solution (worked for me): Remove all toolboxes except the 'Mapping Toolbox'.

I have just come across this problem using Matlab R2018b with java version: 'Java 1.8.0_152-b16 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode'.

On one machine nctoolbox functioned fine, on another (also with R2018b and Java 1.8.0_152-b16) it failed with this error.  The key difference was that the latter has multiple toolboxes installed whilst the former has just the 'Mapping Toolbox'.  Reinstalling Matlab on the second machine with just this toolbox fixed the problem for me.

So possibly one of the other toolboxes brings in another netcdf library or interferes with the java setup?

**Comment by adamcandy** [comment]
@hohonuuli **all** optional toolboxes were installed initially vs. just the Mapping Toolbox -- which isn't particularly helpful.

This could take quite some time to test.  The message is that it is potentially not a problem with Matlab versions (that was the suggestion above) but rather the optional toolboxes installed.

I tend to develop in Python where this type of problem is easier to debug. Is there a way to install and uninstall toolboxes on command that could help?  Or move toolboxes in and out of the toolbox folder, with Matlab restarts?

**Comment by hohonuuli** [comment]
> Is there a way to install and uninstall toolboxes on command that could help? Or move toolboxes in and out of the toolbox folder, with Matlab restarts?

Not that I know of. 

@adamcandy One thing that would help is to run `javaclasspath` in Matlab and post the output here. That will give me a list of possible jar files that might have a conflict with nctoolbox.

**Comment by adamcandy** [comment]
@hohonuuli Good idea! I do not have access to the setup that failed anymore, but will post this when the error appears again.  If anyone else comes across this problem, hopefully this will give them a start to pinning down the issue -- and they can post the failing `javaclasspath` environment.

The working `javaclasspath` environment is attached: [matlab_javaclasspath_output.txt](https://github.com/nctoolbox/nctoolbox/files/2204856/matlab_javaclasspath_output.txt).

**Comment by Jamesjglewis** [comment]
rollback toolbox to 20120109,

**Comment by rtsleight** [comment]
nctoolbox 1.1.0 and a 20130305 version worked for me on Matlab 2018b once the Text Analytics Toolbox was uninstalled. It appears to use the apache tika-app jar (1.14), which has various ucar [dependencies ](https://mvnrepository.com/artifact/org.apache.tika/tika-parsers/1.14) such as netcdf4 4.5.5 and grib 4.5.5.

**Comment by Stratocu1110** [comment]
Encountered a problem similar to some of the described problems with Matlab 2017a-b and 2018a-b when using **Matlab 2019a**.  Specifically, block data GRIB2 reads from OpenDAP failed.  When large block reads failed, I attempted to read small blocks sequentially and found that almost randomly blocks would occasionally be misread while surrounding blocks from the same file were read perfectly.  It seemed like a potential Java version mismatch problem and I ran numerous tests on using two different machines and finally migrated back to Matlab 2018b and NCToolbox 1.1.3, which works.  The Matlab 2017b and NCToolbox 1.1.3 combination also works.  One of the fixes above involving *.jar may solve the problem with Matlab 2019a, not sure, so I attach the full javaclasspath in the attached *.txt file. 
[javaclasspathMatlab2019a.txt](https://github.com/nctoolbox/nctoolbox/files/3214639/javaclasspathMatlab2019a.txt)

**Comment by ahueni** [comment]
Tested the removal of toolboxes on Matlab 2019a. Only remaining toolbox is currently the Mapping Toolbox and the reading of GRIB2 files works just fine.
Possible culprits are: Statistics and Machine Learning Toolbox, Parallel Computing and Curve Fitting Toolboxes.

The error I got before when trying to read a GRIB file was:

    Error using ncdataset (line 81)
    Java exception occurred:
    java.lang.UnsupportedOperationException: This is supposed to be overridden by subclasses.
    	at com.google.protobuf.GeneratedMessage.getUnknownFields(GeneratedMessage.java:262)
    	at
        ucar.nc2.grib.grib2.Grib2IndexProto$GribGdsSection.getSerializedSize(Grib2IndexProto.java:944)

**Comment by wgruner** [comment]
Sorry so late to this thread. A similar issue just hit me using MATLAB R2022a. Here's a slightly more surgical answer regarding protobuf3: https://www.mathworks.com/matlabcentral/answers/1652165-simulink-crashes-with-implemeted-s-function-with-protobuf-and-zeromq-libraries. The idea is just to keep MATLAB from ever loading their special version of Google's protobuf. Who knows what Mathworks did to it, but it doesn't work like the standard version any more. So nixing that JAR as described there might save you from having to get rid of toolboxes. It might also mean that some of your toolboxes stop working, but in that case, you might be able to substitute the protobuf you need in place of the one provided by MATLAB.
